
owner: Unrealdkman 
repo: cemodding-wiki-uptime 

sites:
  - name: Chrome Engine Modding Wiki
    url: https://www.cemodding.wiki
  - name: Email provider
    url: https://mail.privateemail.com


status-website:
  cname: uptime.cemodding.wiki
  logoUrl: https://icons.duckduckgo.com/ip3/www.cemodding.wiki.ico
  name: Chrome Engine Modding Wiki
  theme: night
  favicon: https://icons.duckduckgo.com/ip3/www.cemodding.wiki.ico
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Unrealdkman

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
